_BASE_: ../Base-RetinaNet-PCB.yaml
MODEL:
  WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-101.pkl
  RESNETS:
    DEPTH: 101
OUTPUT_DIR: /home/aoi/AOI_PCB_Retrain_detectron2/detectron2/RetinaNet_2021_11_10_output
