DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: false
DATASETS:
  TRAIN: ("pcb_data_train",)
  TEST: ("pcb_data_test",)
MODEL:
  META_ARCHITECTURE: "RetinaNet"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  RETINANET:
    NUM_CLASSES: 4
    FOCAL_LOSS_ALPHA: 0.25
    FOCAL_LOSS_GAMMA: 2.0
    IOU_THRESHOLDS: [0.01, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.1
    PRIOR_PROB: 0.01
  PIXEL_MEAN: [39.94, 50.83, 38.44] # BGR
  PIXEL_STD: [1.0, 1.0, 1.0] # [42.74, 47.05, 47.55]
  ROI_HEADS:
    NUM_CLASSES: 4
SOLVER:
  BASE_LR: 0.0004
  CHECKPOINT_PERIOD: 1000
  GAMMA: 0.5
  IMS_PER_BATCH: 6
  MAX_ITER: 40000
  STEPS: (10000, 20000, 30000)
INPUT:
  MIN_SIZE_TRAIN: (384, 448, 512, 576, 640, 704, 768)
  MAX_SIZE_TRAIN: 770
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  ROTATION_ANGLES: [0, 90, 180, 270]
VERSION: 2
