_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p37_dla_bifpn_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 5
    NUM_BIFPN: 3
  # ROI_HEADS:
  #   NUM_CLASSES: 4
  CENTERNET:
    # NUM_CLASSES: 4
    POST_NMS_TOPK_TEST: 128
  # RETINANET:
  #   NUM_CLASSES: 4
  WEIGHTS: '/work/u5216579/ctr2_pcb/r50.pkl'
  #PIXEL_MEAN: [123.675, 116.280, 103.530]
  #PIXEL_STD: [58.395, 57.12, 57.375]
  PIXEL_MEAN: [39.94, 50.83, 38.44]
  PIXEL_STD: [42.74, 47.05, 47.55]
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 540000
  BASE_LR: 0.01
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 7500
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 512
  MIN_SIZE_TRAIN: (512, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
  ROTATION_ANGLES: [0, 90, 180, 270]
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: false
SAVE_PTH: true
#DATASETS:
#  TRAIN: ("coco_2017_train","coco_un_yolov4_55_0.5",)
